version: '3'

services:
  templeAP:
    container_name: templeAP
    restart: always
    image: austin39/node
    depends_on:
    - templeDB
    ports:
    - "9000:9000"
    environment: 
    - NPM_CONFIG_LOGLEVEL=info
    volumes:
    - ~/docker/dataAP:/var/lib/dataAP:Z

  templeDB:
    container_name: templeDB
    restart: always
    image: couchdb:1.6.1-couchperuser
    volumes:
    - ~/docker/dataDB:/var/lib/dataDB:Z